
module.exports = {
	CMD_CAPTURE: 'CAPTURE',
	CMD_STOP: 'STOP',
	CMD_UPLOAD: 'UPLOAD',
	CMD_DEPENDENCY_CHECK: 'DPCHECK',

	RES_SUCCESS: 'SUCCESS',
	RES_FAILED: 'FAILED',

	MODULE_FILE: 'FILE',
	MODULE_DIR: 'DIR',

	CMD_ACTION_RUN: 'RUN',
	CMD_ACTION_PAUSE: 'PAUSE'
};
